[package]
name = "hyper-server"
version = "0.1.0"
authors = ["姚子建 <yaozijian110@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12.30"
futures = "0.1.27"
net2 = "0.2.33"
tokio-core = "0.1.17"

