[package]
name = "serde-server"
version = "0.1.0"
authors = ["YaoZijian <yaozijian110@126.com>"]
edition = "2018"

[dependencies]
serde = {version="1.0.91",features=["derive"]}
serde_json = "1.0.39"
serde_yaml = "0.8.9"
